### PR TITLE
Remove conditional len_t as socklen_t is now defined for aarch64-linux-android

### LINKED ISSUE #73: mismatched types error for x86_64-linux-android target
On travis, when building my project for `x86_64-linux-android` target, I got this error message:

```shell
Compiling net2 v0.2.32
error[E0308]: mismatched types
  --> /cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.32/src/socket.rs:40:51
   |
40 |             ::cvt(c::bind(self.inner.raw(), addr, len as len_t)).map(|_| ())
   |                                                   ^^^^^^^^^^^^ expected u32, found i32
```

### PR DESCRIPTION
**Pull request by mehcode**
Fixes #73

### CODE REVIEW

**Comment by russelltg** [comment]
The tests pass for me on aarch64-linux-android through termux. Seems the failure is spurious?

It'd be nice to have this merged.

**Comment by carllerche** [comment]
The mio build is currently broken due to net2 not compiling.

A fix would be appreciated.

**Comment by alexcrichton** [comment]
Looks like there's a merge conflict now, @russelltg mind resolving that?

**Comment by alexcrichton** [comment]
er sorry, @mehcode (my bad!)

**Comment by mehcode** [comment]
No problem. Done @alexcrichton

**Pull request merged**
