### PR TITLE
fix cross compile on target aarch64-linux-android

### PR DESCRIPTION
**Pull request by hlzhang**
issue link: https://github.com/rust-lang-nursery/net2-rs/issues/54

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could the fix be a bit more localized perhaps instead of duplicating the entire function?

**Comment by alexcrichton** [comment]
Thanks for the PR @chshawkn! I fear though that this (and some related PRs) may not be needed though? I see this in Android's header files:

```
#if !defined(__LP64__)
/* This historical accident means that we had a signed socklen_t on 32-bit architectures. */
typedef int32_t __socklen_t;
#else
/* LP64 still has a 32-bit socklen_t. */
typedef uint32_t __socklen_t;
#endif
```

I think that may mean the definition of `socklen_t` is incorrect on aarch64 android?

Can you try running the `libc-test` test suite for aarch64 to see if everything passes?

**Comment by hlzhang** [comment]
@alexcrichton You are right, but I can't fix Android's header file.

**Comment by alexcrichton** [comment]
Ah sorry yeah I didn't mean that, I meant actually that libc itself may be incorrect. I had forgotten though that we recently started running CI, so we know it is indeed correct! In any case, I'll merge and publish a new fix.

**Comment by hlzhang** [comment]
@alexcrichton Thank you!

**Pull request merged**
