### PR TITLE
set/get send/recv buffer size for sockets

### PR DESCRIPTION
**Pull request by arthurprs**
Solves #37

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder if perhaps these methods should have `_size` appended as well? Could you also add a TODO to handle checked casts eventually as well?

**Comment by arthurprs** [comment]
Makes sense. I've updated the commit.

**Comment by arthurprs** [comment]
Yay, it compiles in windows.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
