### PR TITLE
Haiku: no IPv6 available; use SO_KEEPALIVE & FD_CLOEXEC.

### PR DESCRIPTION
**Pull request by jessicah**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Out of curiosity, are the ipv6 constants just not available at all on Haiku? Or do the functions just unconditionally return errors?

**Comment by jessicah** [comment]
IPV6_ADD_MEMBERSHIP/IPV6_DROP_MEMBERSHIP are missing in Haiku. But IPv6 is fairly broken, so figured I'd just return an error for all of them there.

**Comment by alexcrichton** [comment]
Would it be best to let the syscalls themselves return errors? We could update the `cfg_if!` at the top of the file to account for the missing constants, maybe forcing the sycalls to return an error?

I'm just trying to think of the best way to cut down on the `#[cfg]` traffic here.

**Comment by jessicah** [comment]
Hmm, I dunno. IPv6 registers just enough to look like it's functional, but actually isn't. We currently explicitly use IPv4 in WebPositive for example to avoid lots of routing problems.

**Comment by alexcrichton** [comment]
Ok  in that case could we perhaps just let the system return the errors here? These all need to be opted in to anyway so I don't think we'd enable broken functionality by default, for example?

**Comment by kallisti5** [comment]
Definitely seeing an issue due to this one still being outstanding:

```
     Running `rustc --crate-name net2 /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="duration"' -C metadata=272c071196038a44 -C extra-filename=-272c071196038a44 --out-dir /boot/home/rune/target/debug/deps -L dependency=/boot/home/rune/target/debug/deps --extern cfg_if=/boot/home/rune/target/debug/deps/libcfg_if-bf3f0834fba0aadc.rlib --extern libc=/boot/home/rune/target/debug/deps/liblibc-0ccb3d987de5e000.rlib --cap-lints allow`
error[E0432]: unresolved import `libc::TCP_KEEPIDLE`
   --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/ext.rs:663:13
    |
663 |         use libc::TCP_KEEPIDLE as KEEPALIVE_OPTION;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TCP_KEEPIDLE` in the root

error[E0425]: cannot find value `IPV6_ADD_MEMBERSHIP` in this scope
    --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/ext.rs:1115:50
     |
1115 |         set_opt(self.as_sock(), v(IPPROTO_IPV6), IPV6_ADD_MEMBERSHIP,
     |                                                  ^^^^^^^^^^^^^^^^^^^ did you mean `IP_ADD_MEMBERSHIP`?

error[E0425]: cannot find value `IPV6_DROP_MEMBERSHIP` in this scope
    --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/ext.rs:1134:50
     |
1134 |         set_opt(self.as_sock(), v(IPPROTO_IPV6), IPV6_DROP_MEMBERSHIP,
     |                                                  ^^^^^^^^^^^^^^^^^^^^ did you mean `IP_DROP_MEMBERSHIP`?

error[E0308]: mismatched types
  --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/sys/unix/mod.rs:54:23
   |
54 |             ioctl(fd, FIOCLEX);
   |                       ^^^^^^^ expected i32, found u64

error: aborting due to 4 previous errors

Some errors occurred: E0308, E0425, E0432.
For more information about an error, try `rustc --explain E0308`.
error: Could not compile `net2`.
```

**Comment by kallisti5** [comment]
Our Rust 1.40 port still borked due to this one.
```
   Compiling net2 v0.2.33
error[E0432]: unresolved import `libc::TCP_KEEPIDLE`
   --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/ext.rs:663:13
    |
663 |         use libc::TCP_KEEPIDLE as KEEPALIVE_OPTION;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TCP_KEEPIDLE` in the root

error[E0425]: cannot find value `IPV6_ADD_MEMBERSHIP` in this scope
    --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/ext.rs:1115:50
     |
1115 |         set_opt(self.as_sock(), v(IPPROTO_IPV6), IPV6_ADD_MEMBERSHIP,
     |                                                  ^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `IP_ADD_MEMBERSHIP`

error[E0425]: cannot find value `IPV6_DROP_MEMBERSHIP` in this scope
    --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/ext.rs:1134:50
     |
1134 |         set_opt(self.as_sock(), v(IPPROTO_IPV6), IPV6_DROP_MEMBERSHIP,
     |                                                  ^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `IP_DROP_MEMBERSHIP`

error[E0308]: mismatched types
  --> /boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/sys/unix/mod.rs:54:23
   |
54 |             ioctl(fd, FIOCLEX);
   |                       ^^^^^^^ expected i32, found u64
   |
help: you can convert an `u64` to `i32` and panic if the converted value wouldn't fit
   |
54 |             ioctl(fd, FIOCLEX.try_into().unwrap());
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0308, E0425, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `net2`.

To learn more, run the command again with --verbose.
```

**Comment by kallisti5** [comment]
For each item not working:
  * IPV6 ADD/DROP Membership
    * https://dev.haiku-os.org/ticket/15666
  * TCP_KEEPIDLE
    * https://dev.haiku-os.org/ticket/15667

**Comment by pfmooney** [comment]
@kallisti5 @jessicah If you're still interested in getting this integrated, could you rebase onto master and re-test?

**Comment by kallisti5** [comment]
@pfmooney see #103 , it solves things a bit more simply. This one can likely close.

**Comment by pfmooney** [comment]
Closing this in light of #103.  Please re-open if it should be revisited.  Thanks.

**Pull request closed without merging**
