### PR TITLE
Remove special casing for Redox as it is supported by unix target family

### PR DESCRIPTION
**Pull request by jackpot51**
This is an updated version of #112

### CODE REVIEW

**Comment by pfmooney** [comment]
I assume this is a polished up version of @4lDO2's work in #112?
Should there be some attribution for that in the commit message?

**Comment by jackpot51** [comment]
This is a rewritten version of #112. I did not reference #112, since so much has changed.

**Comment by jackpot51** [comment]
(Also, I wrote the commits in #112: https://github.com/deprecrated/net2-rs/pull/112/commits)

**Comment by pfmooney** [comment]
Published as [v0.2.38](https://crates.io/crates/net2/0.2.38)

**Comment by jackpot51** [comment]
Thanks!

**Pull request merged**
