### PR TITLE
Redox OS support

### PR DESCRIPTION
**Pull request by jD91mZM2**
Adds support for Redox OS.

If it is possible to do a release after merging this, that would be great! This crate is used by other crates we're trying to port as well :)

### CODE REVIEW

**Comment by jD91mZM2** [comment]
Bump?

I very much doubt the travis issue is caused by us:
```
thread 'smoke_build_listener_v6' panicked at 'b.bind("::1:0") failed with: Cannot assign requested address (os error 99)', tests/all.rs:41:5
```
(and as you can see it worked on mac and windows and one of the linux tests)

**Comment by jD91mZM2** [comment]
Bump?

**Comment by jD91mZM2** [comment]
YES! Thanks :smile:! Mio can almost be upstreamed because of this, we just need you to bump the version @alexcrichton :)

**Comment by alexcrichton** [comment]
Should be published now!

**Pull request merged**
